### ISSUE TITLE
Test staking contract full stack

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-js#170]
We now have a stable v0.8.0-alpha3 release and integration tests for the staking contract in `wasmd`.

To fully demo this, we need some very high level tests via cosmwasm-js showing the contract in use. It only needs to cover a happy path, but mainly showing client interaction down to the contract working.

**Comment by webmaster128** [comment]
Where/how do you want to write those tests? 0.8.0-alpha.0 is published and can be used from npm

**Comment by ethanfrey** [comment]
I was thinking to add them to cosmwasm-js, but I guess that is a bit ugly. But we do have the erc20 and mask contracts in there already. I think a few demo runs on the staking contract like we do with erc20 would be a simple addition.

If you have a better approach, please let me know.

**Comment by webmaster128** [comment]
Which contract are we talking about exactly? This one https://github.com/CosmWasm/cosmwasm/tree/master/contracts/staking?

One ugly thing I see here is that we don't get a source URL. Also this repo is not well suited to host contract specifics. Having the erc20 connection here is just because we use them as a secondary currency implementation to the bank module in BCP, which will die sooner or later. Then we have some notes in to CLI package, but those are not tested.

We could create a package with unit tests for one contract here and don't publich the package.

**Comment by ethanfrey** [comment]
> We could create a package with unit tests for one contract here and don't publich the package.

Sounds like a good solution.

I would just "port" some of the simplest unit tests - init, bond, and unbond and check with a few queries. This is more to demo usage - we already unit tested the contract itself (in cosmwasm), as well as the sdk integrations (in wasmd)
